module.exports = {
  darkMode: "class",
  content: ["./*.html", "./src/**/*.html"],
  theme: {
    extend: {
      colors: {
        "on-background": "#1b1c1c",
        "secondary-container": "#fed488",
        "tertiary-fixed-dim": "#c8c6c3",
        "outline-variant": "#c4c6cd",
        "on-tertiary-container": "#959491",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#474744",
        "on-error": "#ffffff",
        outline: "#74777d",
        surface: "#fbf9f8",
        "tertiary-fixed": "#e4e2de",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#35485f",
        "inverse-on-surface": "#f2f0f0",
        "surface-container": "#efeded",
        "surface-tint": "#4c6078",
        "surface-container-low": "#f5f3f3",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#e9c176",
        "on-secondary-container": "#785a1a",
        "on-primary-fixed": "#061d32",
        "inverse-primary": "#b4c8e4",
        "on-secondary-fixed-variant": "#5d4201",
        "on-primary-container": "#8296b0",
        "secondary-fixed": "#ffdea5",
        "surface-variant": "#e4e2e2",
        "surface-dim": "#dbd9d9",
        background: "#fbf9f8",
        "on-secondary-fixed": "#261900",
        "primary-container": "#1a2e44",
        "on-primary": "#ffffff",
        "surface-bright": "#fbf9f8",
        "primary-fixed": "#d1e4ff",
        "inverse-surface": "#303030",
        "error-container": "#ffdad6",
        "tertiary-container": "#2c2d2b",
        "on-surface": "#1b1c1c",
        "surface-container-highest": "#e4e2e2",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#b4c8e4",
        secondary: "#775a19",
        "on-surface-variant": "#43474d",
        primary: "#03192e",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#1b1c1a",
        "surface-container-high": "#eae8e7",
        tertiary: "#181816",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "24px",
        "container-max": "1120px",
        "margin-desktop": "64px",
        unit: "8px",
        "section-gap": "120px",
      },
      fontFamily: {
        "headline-md": ["EB Garamond", "serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "quote-text": ["EB Garamond", "serif"],
        "label-caps": ["Manrope", "sans-serif"],
        "headline-sm": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "44px", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "quote-text": ["22px", { lineHeight: "34px", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
